#!/bin/bash
set -e

# this script is based on a template used by multiple AppImages, exact source is unknown

if [ ! -z "$DEBUG" ] ; then
  env
  set -x
fi

THIS="$0"
# http://stackoverflow.com/questions/3190818/
args=("$@")
NUMBER_OF_ARGS="$#"

if [ -z "$APPDIR" ] ; then
  # Find the AppDir. It is the directory that contains AppRun.
  # This assumes that this script resides inside the AppDir or a subdirectory.
  # If this script is run inside an AppImage, then the AppImage runtime likely has already set $APPDIR
  path="$(dirname "$(readlink -f "${THIS}")")"
  while [[ "$path" != "" && ! -e "$path/$1" ]]; do
    path=${path%/*}
  done
  APPDIR="$path"
fi

get_target()
{
  if [ "${1:-}" = "ModOrganizer" ] || [ "${1:-}" = "nxmhandler" ]; then
    printf '%s' "$1"
    return 0
  fi

  # default
  printf '%s' "ModOrganizer"
}

target="$(get_target "${1:-}")"

# Remove subcommand from arguments
if [ "${1:-}" = "$target" ]; then
  unset 'args[0]'
  NUMBER_OF_ARGS=$((NUMBER_OF_ARGS-1))
fi

BIN="$APPDIR/usr/bin/$target"

if [ -z "$APPIMAGE" ] ; then
  APPIMAGE="$APPDIR/AppRun"
  # not running from within an AppImage; hence using the AppRun for Exec=
fi

if [ $NUMBER_OF_ARGS -eq 0 ] ; then
  exec "$BIN"
else
  exec "$BIN" "${args[@]}"
fi
