services:
  build:
    build:
        context: .
    volumes:
      - /dev/fuse:/dev/fuse # required for linuxdeploy
      - ${OUTPUT_DIR:-./}build:/root/build
      - ${OUTPUT_DIR:-./}mob:/root/mob
      - ${OUTPUT_DIR:-./}ccache:/root/ccache
      - ${OUTPUT_DIR:-./}vcpkg:/root/vcpkg
    environment:
      - EXTRA_QT_MODULES=${EXTRA_QT_MODULES}
      - EXTRA_PLATFORM_PLUGINS=${EXTRA_PLATFORM_PLUGINS}
      - LINUXDEPLOY_EXCLUDED_LIBRARIES=${LINUXDEPLOY_EXCLUDED_LIBRARIES}
      - USE_CCACHE=${USE_CCACHE}
      - DO_BUILD=${DO_BUILD}
      - DO_RELEASE=${DO_RELEASE}
      - UPDATE_MOB=${UPDATE_MOB}
    cap_add:
      - SYS_ADMIN # required for linuxdeploy
