services:
  build:
    build:
        context: .
    volumes:
      - /dev/fuse:/dev/fuse # required for linuxdeploy
      - ${OUTPUT_DIR:-./}build:/root/build
      - ${OUTPUT_DIR:-./}mob:/root/mob
      - ${OUTPUT_DIR:-./}ccache:/root/ccache
      - ${OUTPUT_DIR:-./}vcpkg/buildtrees:/root/vcpkg/buildtrees # to debug vcpkg build failures
    environment:
      - EXTRA_QT_PLUGINS=${EXTRA_QT_PLUGINS}
      - EXTRA_PLATFORM_PLUGINS=${EXTRA_PLATFORM_PLUGINS}
      - LINUXDEPLOY_EXCLUDED_LIBRARIES=${LINUXDEPLOY_EXCLUDED_LIBRARIES}
      - CMAKE_C_COMPILER_LAUNCHER=${COMPILER_LAUNCHER}
      - CMAKE_CXX_COMPILER_LAUNCHER=${COMPILER_LAUNCHER}
    cap_add:
      - SYS_ADMIN # required for linuxdeploy
