name: Build Mob

on:
  push:
    branches: master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            shell: pwsh
            ext: ps1
          - os: ubuntu-24.04
            shell: bash
            ext: sh

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build Mob
        shell: ${{ matrix.shell }}
        run: ./bootstrap.${{ matrix.ext }} -Verbose
