name: Build Mob

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  VCPKG_BINARY_SOURCES: ${{ vars.AZ_BLOB_VCPKG_URL != '' && format('clear;x-azblob,{0},{1},readwrite', vars.AZ_BLOB_VCPKG_URL, secrets.AZ_BLOB_SAS) || '' }}

jobs:
  build_windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v6
      - name: Build Mob
        shell: pwsh
        run: |
          $env:VCPKG_ROOT = $env:VCPKG_INSTALLATION_ROOT
          ./bootstrap.ps1 -Verbose

  build_linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Install GCC 16
        run: |
          sudo apt-get install -y --no-install-recommends software-properties-common
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get install -y --no-install-recommends gcc-16 g++-16

          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-16 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-16 100
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-16 100
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-16 100

      - name: Build Mob
        run: |
          export VCPKG_ROOT="$VCPKG_INSTALLATION_ROOT"
          ./bootstrap.sh -Verbose
